apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: vote-api
  - name: git-url
    value: http://github.com/Spider-Art/vote-api.git
  - name: git-revision
    value: master
  - name: IMAGE
    value: "image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api"
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: storage-workspace